name: kerchunk-cookbook-dev
channels:
  - conda-forge
dependencies:
  - cfgrib
  - jupyter-book
  - jupyterlab
  - jupyter_server<2
  - pip
  - fsspec
  - numcodecs
  - numpy
  - tqdm
  - ujson
  - xarray
  - zarr
  - pip:
      - sphinx-pythia-theme
      - git+https://github.com/fsspec/kerchunk.git
