name: kerchunk-cookbook-dev
channels:
  - conda-forge
dependencies:
  - jupyter-book
  - jupyterlab
  - jupyter_server<2
  - pip
  - fsspec
  - numcodecs
  - numpy
  - ujson
  - zarr
  - pip:
      - sphinx-pythia-theme
